---
- hosts: dockerhost

  tasks:
    - name: stop existing container
      command: docker stop regapp-server
      ignore_errors: yes 

    - name: remove the conaitner
      command: docker rm regapp-server 
      ignore_errors: yes

    - name: remove image
      command: docker image rm  masterpece/regapp:v1
      ignore_errors: yes

    - name: create container
      command: docker run -d --name regapp-server -p 8082:8080 masterpece/regapp:v1

