---
- hosts: kubernetes
  #become: true
  user: ansadmin

  tasks:
  - name: deploy regapp on kubernetes
    command: kubectl apply -f deploy2.xml

  - name: expose service
    command: kubectl apply -f service2.yml
