apiVersion: v1
kind: Service
metadata:
  name: celestin-service
  labels:
    app: helloapp 
spec:
  selector:
    app: helloapp 

  ports:
    - name: hello-port
      port: 8181
      targetPort: 8181

  type: LoadBalancer